export const HANDSHAKE = 'HANDSHAKE';
export const INITIALIZE_ROOMS = 'INITIALIZE_ROOMS';
export const INITIALIZE_MARKERS = 'INITIALIZE_MARKERS';
export const RECONNECTED = 'RECONNECTED';
export const ROOM_STATUSES_UPDATE = 'ROOM_STATUSES_UPDATE';
export const NEW_ROOM_PING = 'NEW_ROOM_PING';
export const ROOM_TEMPERATURE_UPDATE = 'ROOM_TEMPERATURE_UPDATE';
export const ROOM_MOTION_UPDATE = 'ROOM_MOTION_UPDATE';
