export const HANDSHAKE = 'HANDSHAKE';
export const INITIALIZE_ROOMS = 'INITIALIZE_ROOMS';
export const INITIALIZE_MARKERS = 'INITIALIZE_MARKERS';
export const RECONNECTED = 'RECONNECTED';
export const ROOM_STATUSES_UPDATE = 'ROOM_STATUSES_UPDATE';
export const NEW_ROOM_PING = 'NEW_ROOM_PING';
export const TEMPERATURE_UPDATE = 'TEMPERATURE_UPDATE';
export const MOTION_UPDATE = 'MOTION_UPDATE';
